- docs/Basic-Tutorial.md
Docs for #107 was added.
Full inscriptions list who can be replaced to custom ones.
---
> Docs: #110 - Need a full key list of localization for #107

- README.md
Just little refactoring for docs - ISO language code.
> Refactor: #110 - ISO language code

- src/js/ui/template/submenu/filter.js
ref: Issue #138
Modify filter submenu text "Grayscale" to "Gradient transparency"
---
> fix: Modify title of filter subMenu name "Grayscale" (fix #138)

- src/css/main.styl
Fixes CSS typo issue.
ref: #175
---
> fix: Modify CSS typo (fixes #175)

- examples/example01-includeUi.html
- examples/example02-useApiDirect.html
- examples/example03-mobile.html
- examples/js/service-basic.js
- examples/js/service-mobile.js
- index.d.ts
- Change basic example & mobile example colorPicker dependency version to v2.2.0.
ref: #191 
---
> fix: Change basic example's dependency version

- index.d.ts
- test/types/type-tests.ts
- [] Docs have been added/updated (for bug fixes/features)
- Add `undefined` to IGraphicObjectProps property type
ref: #190
---
> fix: Add IGraphicObjectProps property type 'undefined' (fix: #190)

- examples/js/service-basic.js
fixes #218 
- Change ES6 syntax to ES5 for [Use API Direct example](http://nhn.github.io/tui.image-editor/latest/examples/example02-useApiDirect.html) page.
---
> fix: Change "Use API Direct" example page's ES6 syntax to ES5  fix #218 

- examples/example01-includeUi.html
- examples/example02-useApiDirect.html
- examples/example03-mobile.html
- index.d.ts
- src/js/imageEditor.js
- src/js/ui.js
- src/js/ui/crop.js
- src/js/ui/draw.js
- src/js/ui/filter.js
- src/js/ui/flip.js
- src/js/ui/icon.js
- src/js/ui/mask.js
- src/js/ui/rotate.js
- src/js/ui/shape.js
- src/js/ui/submenuBase.js
- src/js/ui/text.js
- src/js/ui/tools/colorpicker.js
> fix: Do not send GA when 'usageStatistics: false' (fix #220)

- examples/js/service-basic.js
* ie에서 실행안되는 예제가 있어서 service-basic.js 코드 수정
* 화살표 함수를 일반 함수로 변경
> fixed: sample example file for ie

- docs/COMMIT_MESSAGE_CONVENTION.md
> chore: Typo correction guide document

- exampleTest.js
- tuidoc.config.json
> change option globalErrorLogVariable

- src/js/component/text.js
- src/js/imageEditor.js
- test/text.spec.js
* addText 에 default값이 true인 autofocus옵션 추가.
* autofocus옵션이 true이면 오토포커싱 시키고 텍스트가 전체 선택되도록함
---
> feat: added text auto focus option

- src/js/command/changeIconColor.js
- src/js/consts.js
- src/js/extension/blur.js
- src/js/ui/filter.js
* not work blur filter #445 
* change to pass the blur filter option
* not work redo/undo command of icon color change #448 
* fix object destructuring of icon color change undo command
---
> fix: not work blur filter, not work redo/undo command of icon color change

- src/js/component/text.js
Fix an bug that the line-through decoration did not work because of a misspelling
---
> fix: text line-through decoration [#453]

- .github/workflows/detectRuntimeError.yml
> fix: github action error

- apps/vue-image-editor/README.md
> imported CSS in README

- apps/image-editor/examples/js/service-basic.js
> fix: group selection object position when undo, redo in API direct page [#522]

- apps/image-editor/src/js/consts.js
- apps/image-editor/src/js/imageEditor.js
> fix: fire object modified event when cropzone changed [#519]

- apps/image-editor/src/js/extension/cropzone.js
> fix: resize cropzone with ratio by pressing shift key

- apps/image-editor/src/js/component/zoom.js
- apps/image-editor/src/js/consts.js
> fix: start hand mode when text editing [#555, #556]

- apps/image-editor/src/js/component/zoom.js
> fix: unable to press spacebar in HTML input, textarea [#556]

- README.md
- [x ] It's right issue type on title
Fix invalid links. (The existing link shows 404 pages.)
---
> docs: Modify the repository link

- .github/workflows/publish-npm.yml
> chore: add `publish-npm.yml`

- .github/workflows/publish-npm.yml
> chore: actions cache test

- .github/composite-actions/build-package/action.yml
- .github/composite-actions/install-dependencies/action.yml
- .github/composite-actions/publish-cdn/action.yml
- .github/composite-actions/publish-docs/action.yml
- .github/composite-actions/publish-package/action.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-npm.yml
- .github/workflows/publish-wrapper.yml
- apps/image-editor/package.json
- apps/image-editor/scripts/publishToCDN.js
- apps/image-editor/scripts/updateWrapper.js
- package-lock.json
- package.json
add github actions for publish
---
> chore: add actions for publish

- README.md
* fix grammar of README.md
---
> docs: correct grammar of README
