nhn/tui.image-editor

src/js/graphics.js
src/js/imageEditor.js
test/imageEditor.spec.js

* 텍스트 편집시 backspace가 동작하지 않는 부분을 해결
- object 삭제할때의 이벤트 처리와 겹치기 때문에 object가 선택되지 않았다면 preventdefault가 실행되지 않도록 변경
* 잘못된 jsdoc 주석 변경

fix: Backspace does not work at text editing

---

src/js/component/icon.js
test/icon.spec.js

* 커스텀 아이콘 추가시 자바스크립트 에러가 발생되는 부분을 해결 (커스텀 아이콘은 drag로 추가되는 부분이 아니기때문에 dragevent가 생기면 안된다)
- defaultIconPath에 포함된 타입이 아닐경우 이벤트가 발생하지 않도록 예외처리
- 관련해서 add() 메서드 리팩토링 -  (_addDragWith()) 메서드를 추가하여 코드 분리

fix: add custom icon error

---

src/js/action.js
src/js/ui.js
test/ui.spec.js

- init 이미지가 없는 상태에서 이미지`Load` 버튼이 정상 동작하지 않는 문제를 수정
- addLoadEvent() 를 초기 이미지가 없는 상태에서도 항상 호출하도록 변경
- 초기 이미지가 없는 상태에서 이미지 로드시 이미지사이즈 상태를 업데이트 해주도록 변경
- ui.resizeEditor() 메서드를 api로 노출 하도록  jsdoc 수정
- http://10.78.9.21:8083/examples/example01-includeUi.html

fix: load-image init event error

---

src/css/buttons.styl
src/js/action.js
src/js/component/cropper.js
src/js/graphics.js
src/js/imageEditor.js
src/js/ui/crop.js
src/js/ui/template/submenu/crop.js
test/cropper.spec.js

Adds crop selection presets (square, 3:2, 4:3, 5:4, 7:5, 16:9)

---

README.md
src/js/ui.js
src/js/ui/crop.js
src/js/ui/draw.js
src/js/ui/filter.js
src/js/ui/flip.js
src/js/ui/icon.js
src/js/ui/locale/locale.js
src/js/ui/mask.js
src/js/ui/rotate.js
src/js/ui/shape.js
src/js/ui/submenuBase.js
src/js/ui/template/controls.js
src/js/ui/template/mainContainer.js
src/js/ui/template/submenu/crop.js
src/js/ui/template/submenu/draw.js
src/js/ui/template/submenu/filter.js
src/js/ui/template/submenu/flip.js
src/js/ui/template/submenu/icon.js
src/js/ui/template/submenu/mask.js
src/js/ui/template/submenu/rotate.js
src/js/ui/template/submenu/shape.js
src/js/ui/template/submenu/text.js
src/js/ui/text.js
src/js/util.js

[Localization](https://github.com/nhnent/tui.image-editor/issues/45) [feature](https://github.com/nhnent/tui.image-editor/issues/85) was added. Please, let me know if I need to change something into my PR.
Maybe tests should be added.
Also, maybe this feature must to change current npm version of tui.image-editor.
---

feat: Localization feature was added #45

---

src/css/position.styl

Currently the tooltip's get cut or weirdly wrapped when the menu is on the left or right:
This patch removes the arbitrary width (not needed) and stops wrapping on the tooltips.

Fix: Fix width of tooltip when menu is left or right

---

src/css/buttons.styl
src/js/ui.js
src/js/ui/template/style.js

Issue: #115 
- Initialize and register default icon sets regardless `initMenu` option's value
- Add button svg for `icon-start-2`
- Correct mistyped JSDoc parameter types
---

fix: Initialize UI defaultIcons without initial selected menu option. (fix #115)

---

src/js/component/flip.js
src/js/component/imageLoader.js
src/js/component/rotation.js
src/js/graphics.js
src/js/imageEditor.js
src/js/ui.js
test/command.spec.js
test/drawingMode.spec.js
test/filter.spec.js
test/graphics.spec.js
test/promiseApi.spec.js

jquery 레퍼로 싸여있는 엘리먼트 정보를 받을때, 타입스크립트 `index.d.ts` 타입 지원을 위해
"@types/jquery":  디펜던시를 추가해야 하는 이슈가 있으므로, 굳이 필요가 없는 jquery 레퍼 엘리먼트를 받는 부분을 제거하여 필요없는 디펜던시 추가를 막기 위해 수정하였습니다.

feat: Remove jQuery selector method and jQuery elements from code

---

index.d.ts
package-lock.json
package.json

* chore: remove jquery type
---

chore: Remove jQuery type

---

index.d.ts
test/types/tsconfig.json

Remove **esModuleInterop**, **allowSyntheticDefaultImports** options in `tsconfig.json`.
Change 'tui-image-editor' class export type to `default` in `index.d.ts`.
---

fix: Change 'tui-image-editor' export type to default export (fix #142)

---

src/css/main.styl
src/js/ui/template/controls.js
src/js/ui/template/mainContainer.js

Change UI Load button Tag 'button' to 'div'.
Because of input tag in button tag is invalid html, the button in Firefox does not working as expected. 
---

fix: Change loadButton tag to div (fix #137)

---

src/js/component/shape.js
src/js/interface/component.js

Add shape on mouseClick without mouseMove.
---

fix: Add shape on mouseClick without mouseMove (fix #144)

---

src/js/ui/tools/colorpicker.js

Change show state when color changes & initial color-picker opening.
---

fix: Do not fire "changeShow" event when ColorPicker's color not changed (fix #131)

---

README.md
index.d.ts
test/types/type-tests.ts

In typescript, to import module by replacing entire exports object(`module.exports  = {}`) must use `import someModule = require('that-module');`. [ref.](https://www.typescriptlang.org/docs/handbook/modules.html)
`module.exports = {}` is not equivalent `export default {}`. Default export matches `module.exports.default = {}`.
```js
module.exports = ImageEditor;
// --------------------------------------
import ImageEditor = require('tui-image-editor');
```
```js
module.exports.default = ImageEditor;
// or
export default ImageEditor;
// --------------------------------------
import ImageEditor from 'tui-image-editor';
```
Change module exporting type `default` to commonjs pattern.
ref: #159 
---

fix: Change module exporting type (fix #159)

---

src/css/main.styl

- Add div element selector for default UI's menu position top div button
ref: #185 
---

fix: Add menu position top's div button style (fix: #185)

---

src/css/main.styl
src/css/position.styl
src/js/ui.js
src/js/ui/template/controls.js

- Remove `title` attribute from menu buttons for disable browser's default tooltip.
ref: #187 
---

fix: Remove title attribute for disable browser's default tooltip (fix: #187)

---

index.d.ts
src/css/position.styl
src/js/ui/template/style.js

* whiteTheme  스킨일경우 필터메뉴의 체크박스가 안보이는 버그 수정 (이전 멀티인스턴스 관련 css  수정의 사이드 이팩트)
* 서브메뉴 타이틀이 top일 경우 아래와 같이 메뉴가 편집영역을 덮어버리는 버그 수정
* ![스크린샷 2019-12-10 오전 11 57 37](https://user-images.githubusercontent.com/35218826/70491308-4b1ae000-1b44-11ea-9650-e086377ae8f1.png)

fix: white theme style bug

---

src/js/command/addText.js
src/js/command/changeTextStyle.js
src/js/command/setObjectProperties.js
src/js/component/text.js
src/js/graphics.js
src/js/imageEditor.js
src/js/ui/text.js

Fix related to issue #221 and PR https://github.com/nhn/tui.image-editor/pull/225
Updates the documentation related to
textDecoration and line-through and 2 instances where they wrong key
was used in code configuration. 
close: resolves some documentation related to the bug but not the bug.
---

Fix: Fix spelling of textDecoration and line-through

---

src/js/component/cropper.js
src/js/util.js
test/cropper.spec.js

* https://github.com/nhn/tui.image-editor/issues/114
* '408x312'이미지에 '16 : 9 '비율을 적용하면'getCropzoneRect () '메소드가 null을 반환합니다.
* 원본 이미지의 크기에 맞게 16 : 9 의 비율값을 이용하여 cropzone 크기 계산시 부동 소수점 계산 오차에 의해 width값에 +0.00000000003 의 오차가 생김
* (보통의 경우에 미세한 오차는 큰 상관이 없음 하지만 아래와 같은 경우에 문제가 생김)
* width값 오차로 인해 left 값 계산시 `left = (originalWidth - width) / 2` 또한 오차가 생기고 left가 마이너스 값이 되면서 캔버스 유효 범위를 벗어나게됨.
* 부동 소수점 오차를 해결하기 위해 width, height 최종 결과값에 소수점 2 번째 자리에서 반올림 하여 0.00000000003의 오차를 해결 (오차 해결방식은 fabricjs 코드를 참고함)
* width, height 값만 정확하면 그에 따른 left, top 값은 부동소수점 오차가 있어도 isValid 값에 영향을 받지 않게 되는 값을 갖게 되므로 문제가 없게됨
---

fix: fixed setCropzoneRect floating point bug (fix #114)

---

src/js/extension/cropzone.js
test/cropzone.spec.js

* https://github.com/nhn/tui.image-editor/issues/118
* ![](https://user-images.githubusercontent.com/35218826/71879868-6c3a1500-3172-11ea-83dc-2042b22ecf1e.png)
* cropzone을 가장자리로 이동시킨후 크기조정을 하면 cropzone이 켄버스 영역 밖으로 벗어나버림
* Object 리사이즈를 위해 컨트롤을 선택할경우 각 방향의 8개의 컨트롤중 어느것을 선택하여 리사이즈 중인지 판별하기 위하여 `Object.__corner` 값을 이용하여 판별함
* 리사이즈중 마우스 포인터가 켄버스 영역을 벗어났다가 다시 돌아올경우 Object.__corner 값이 정상적인 값을 리턴하지 않고 0을 리턴하기 시작함
* Object.__corner 값이 0을 리턴하면서 계산식이 잘못되어 cropzone이 켄버스 영역을 벗어나게됨
* 불안전한 Object.__corner값을 이용하지 않고 fabricjs개발자가 권장하는 scaling 핸들러의 `fEvent.transform.corner` 값을 통해 선택된 컨트롤을 판별하여 버그 없이 동작하게 함
* https://github.com/fabricjs/fabric.js/issues/5131
---

fix: change the way corner type information is obtained (fix #118)

---

src/js/consts.js
src/js/ui/draw.js
src/js/ui/filter.js
src/js/ui/rotate.js
src/js/ui/shape.js
src/js/ui/text.js
src/js/ui/tools/range.js
test/uiRange.spec.js

* https://github.com/nhn/tui.image-editor/issues/183
* rotate 기능의 값을 1도씩 정교하게 수정할 수 없음
* slide ui의 input 값을 통하여 값을 보다 정교하게 변경할 수 있도록 개선
* tools/range.js 에서 input 영역의 값 표시와 변경에 관련된 이벤트를 직접 처리할수 있도록 역할 강화
* tools/range.js 사용시 소수점 단위로 정교하게 다뤄야 하는 경우와 정수단위로 값을 다뤄야 하는 경우가 있으므로 소수점값 변경을 range 컴포넌트가 직접 고려하도록 useDecimal 옵션 추가
* range 컴포넌트로 값 변경시 변경과정에서 undo, redo stack 반영 및 되돌리기가 매끄럽게 동작하지 않는 부분은 해당 개선 이슈와는 관련이 없는 기존 버그로.. 다음 차례의 이슈로 바로 이어서 작업 예정.

feat: change input bindig (#183)

---

src/js/action.js
src/js/command/changeShape.js
src/js/component/shape.js
src/js/consts.js
src/js/imageEditor.js
src/js/interface/command.js
src/js/ui/shape.js
test/command.spec.js

* https://github.com/nhn/tui.image-editor/issues/315
* https://github.com/nhn/tui.image-editor/issues/310
* shape 기능의 `changeShape` 명령에 대한 undo 또는 redo 실행시 상태가 정확히 되돌려지지 않음
* rotate 기능에 구현된 부분을 참고하여 변경 (isSilent 플래그를 추가하여 운영)
* strokeWidth 가 변경될때는 마지막 스택의 텍스트 스타일  값을 항상 알고 있도록 변경하고, 그 값을 기준으로 동작 하도록 변경
* redo 실행시 이미 undoData가 있으면 값이 변경되지 않도록 수정

fix: fixed undo redo bug for shape menu (fixed #315 #310)

---

src/js/action.js
src/js/command/applyFilter.js
src/js/command/changeShape.js
src/js/command/changeTextStyle.js
src/js/component/filter.js
src/js/consts.js
src/js/imageEditor.js
src/js/interface/command.js
src/js/ui/filter.js
src/js/ui/template/submenu/filter.js
test/filter.spec.js

* https://github.com/nhn/tui.image-editor/issues/310
* filter 의 slider UI에서 Drag 하는 동안에는 undoStack에 반영되면 안됨
* rotate 기능에 구현된 부분을 참고하여 변경 (isSilent 플래그를 추가하여 운영)

feat: undo redo for slider filter (fixed #310)

---

src/js/component/rotation.js
src/js/consts.js
src/js/graphics.js
src/js/imageEditor.js
test/imageEditor.spec.js

* https://github.com/nhn/tui.image-editor/issues/285
* 사용자가 참조할수 있는 object 회전 이벤트 리스터가 없음
* objectRotated 이벤트 리스너 추가

feat: add object rotated event listener

---

src/js/action.js
src/js/ui.js
test/action.spec.js

* https://github.com/nhn/tui.image-editor/issues/266
* redo, undo, reset, delete, delete-all 에 해당하는 툴팁이 안뜸
* 툴팁이 나오도록 하는 누락된 tooltip-content 애트리뷰트 추가

fix: help menu tooltip (fixed #266)

---

karma.conf.js
src/js/consts.js
src/js/imageEditor.js
src/js/ui.js
src/js/ui/crop.js
src/js/ui/draw.js
src/js/ui/filter.js
src/js/ui/flip.js
src/js/ui/icon.js
src/js/ui/mask.js
src/js/ui/rotate.js
src/js/ui/shape.js
src/js/ui/submenuBase.js
src/js/ui/text.js
src/js/ui/tools/colorpicker.js
src/js/util.js
test/action.spec.js
test/fixtures/icon-a.svg
test/fixtures/icon-b.svg
test/fixtures/icon-c.svg
test/fixtures/icon-d.svg
test/theme.spec.js
test/ui.spec.js

* https://github.com/nhn/tui.image-editor/issues/334
* imageEditor.destroy() 시 UI는 destroy처리가 안되어 있음
* destroy 코드 추가

fix: remove instance for ui (fixed #334)

---

src/js/ui.js
test/ui.spec.js

* https://github.com/nhn/tui.image-editor/issues/340
착각으로 인해 잘못 구현된 _getEditorDimension을 제거하고 _getCanvasMaxDimension로 대체
이미지 크기가 .tui-image-editor 영역의 크기보다 클 경우 스크롤이 생기기 하고 싶어서 넣은 코드였으나, 알고보니 .tui-image-editor-wrap에서 스크롤이 생기고
.tui-image-editor는 scale된 실제 캔버스 크기과 같으면 되므로 잘못된 코드를 제거했습니다.
---

fix: image editor rotate bug (fix #340)

---

src/js/component/cropper.js
src/js/component/shape.js
src/js/consts.js
src/js/graphics.js
test/cropper.spec.js

* https://github.com/nhn/tui.image-editor/issues/101
* 크롭존에 수평기울이기, 수직기울이기 옵션이 허용되어 있어서 크롭존이 찌그러지는 경우가 발생
* DEFAULT 옵션을 정의하여 찌그러지지 않도록 옵션 설정
---

feat: cropzone default option change (fix #101)

---

src/js/graphics.js
test/command.spec.js
test/graphics.spec.js

다중 선택된 객체들을 백스페이스로 삭제 후 되돌리기(undo) 를 했을때 되돌려진 객체의 포지션이 정확하지 않음
`graphics.getActiveObjectIdForRemove` 에서 멀티셀렉트된 객체들을 한번에 삭제하기위해 group을 만들어줄때 group의 포지션을 모름으로, 되돌릴때 x, y (0, 0)의 잘못된 포지션으로 되돌려줌
삭제를 위한 group을 만들때 삭제되기 전의 오리지날 포지션을 정확히 넣어줌
---

fix: group object delete after restore position (fix #356)

---

.eslintignore
exampleTest.js
examples/js/service-mobile.js

fixed bug example test

---

README.md
bower.json
examples/example01-includeUi.html
examples/example02-useApiDirect.html
examples/example03-mobile.html
examples/js/service-basic.js
package-lock.json
package.json
src/js/action.js
src/js/component/shape.js
src/js/component/text.js
src/js/consts.js
src/js/graphics.js
src/js/helper/shapeFilterFillHelper.js
test/graphics.spec.js

[작업내역](https://nhnent.dooray.com/project/1800522864831118893/2886335221383714239?contentsType=contents&workflowIds=all&userWorkflowIds=all)
---

feat: update fabric version to 4.2.0 [#461]

---

src/js/action.js
src/js/component/icon.js
src/js/consts.js
src/js/drawingMode/icon.js
src/js/graphics.js
src/js/helper/selectionModifyHelper.js
src/js/imageEditor.js
src/js/ui/icon.js
test/action.spec.js
test/icon.spec.js
test/promiseApi.spec.js

By adding the icon drawing mode, the size of the icon is properly reflected when undo/redo the icon.
So, issues #74 , #441 have been resolved.
---

feat: add icon drawing mode [#74, #441]

---

src/js/graphics.js

Fix a bug that setBrush API did not work while line drawing
---

fix: not apply setBrush API when LINE_DRAWING [#409, #418]

---

apps/vue-image-editor/README.md

There is an issue with hyperlinking in the README file of vue image editor app.

correction in document URL in README of vue image editor

---

apps/image-editor/webpack.config.js

fix CSP issue when build on production webpack
fix: unsafe-eval by using devtool: source-map
https://github.com/nhn/toast-ui.react-image-editor/issues/30#issue-667395712

fix CSP issue when build on production webpack

---

apps/image-editor/src/js/command/addText.js

fix: undo changed text (#521)

---

apps/image-editor/src/js/component/zoom.js
apps/image-editor/src/js/graphics.js

fix: not remove key event listener when vue component loaded [#560]

---

apps/image-editor/src/js/consts.js
apps/image-editor/src/js/imageEditor.js
apps/image-editor/src/js/ui.js
apps/image-editor/src/js/ui/draw.js
apps/image-editor/src/js/ui/filter.js
apps/image-editor/src/js/ui/icon.js
apps/image-editor/src/js/ui/shape.js
apps/image-editor/src/js/ui/submenuBase.js
apps/image-editor/src/js/ui/text.js

Fixed a bug that removed the object when editing the hex input of the color picker.
* AS-IS
* ![asis](https://user-images.githubusercontent.com/76134395/102418192-dda95700-3fc2-11eb-9309-3b8c50051f01.gif)
* TO-BE
* Object is not removed, only the input box is modified.
* Solution
* For each input box of submenus, add focus and blur event handler to generate `inputBoxEditingStarted` and `inputBoxEditingStoped` events to determine whether the color(hex) value is being edited or not.
* The events in the submenu are received by the ui and re-fire, and the events are received in the imageEditor to know if the input box of the color picker is being editted.
---

fix: removes the object when editing hex inputs of the color picker. (fix #504)

---

apps/image-editor/src/js/action.js
apps/image-editor/src/js/ui/filter.js

Fix a bug that does not uncheck the filter's check box when a reset or image is loaded after applying the filter
* AS-IS
* ![화면-기록-2021-04-01-오후-5 07 09](https://user-images.githubusercontent.com/28647773/113263646-fe48b300-930c-11eb-8e5f-56873f9db19d.gif)
* TO-BE
* Uncheck the filter box when resetting or loading images after applying the filter.
* Solution
* Add logic to uncheck all filter check boxes when reset or image load
---

fix: not uncheck filter's checkbox when reset image [fix #552]

---

package-lock.json

`➜  tui.image-editor git:(master) npm install
added 868 packages, and audited 869 packages in 10s
4 vulnerabilities (2 low, 1 moderate, 1 high)
To address all issues, run:
npm audit fix
Run `npm audit` for details.
➜  tui.image-editor git:(master) ✗ npm audit
minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
fix available via `npm audit fix`
node_modules/meow/node_modules/minimist
node_modules/minimist
mkdirp  0.4.1 - 0.5.1
Depends on vulnerable versions of minimist
node_modules/mkdirp
ssri  5.2.2 - 6.0.1 || 7.0.0 - 8.0.0
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/565
fix available via `npm audit fix`
node_modules/ssri
y18n  <3.2.2||=4.0.0||>=5.0.0 <5.0.5
Severity: high
Prototype Pollution - …

fix: update package-lock to fix security issues (fix #585)

---

apps/image-editor/src/js/ui/template/submenu/resize.js

Hi all, this PR fixes a visual issue with labels on the resize feature while using `menuBarPosition: "left|right"`. When using either of those two modes the "px" labels are not inline and appear on a different line. Screenshots show the before/after.
Before:
After:

fix: Inline "px" labels for resize image feature

---

apps/image-editor/index.d.ts

- improve `applyFilter` function's options type (fix #616)
---

refactor: improve `applyFilter` type (fix #616)

---

apps/image-editor/src/js/component/cropper.js
apps/image-editor/tests/cropper.spec.js

Problem (how it is now): 
- in crop mode
- choose a preset ratio (eg. 16/9)
- draw/make a new cropzone
- the aspect ratio is not restricted to the chosen preset ratio (not like when resizing the cropzone by the corners)
This PR fixes that problem. When you now draw/make a new cropzone while having selected a  preset ratio, that preset ratio is now respected.

fix: respect presetRatio on new cropzone

---

apps/image-editor/src/js/action.js
apps/image-editor/src/js/consts.js
apps/image-editor/src/js/ui/resize.js

Hi all, in this PR I propose a change to the resize module. Currently the sliders allow resizing up to 4088px (Any particular reason or just arbitrary?); after this patch the images will not be able to be resized over 100% to disallow upscaling. Not only does the application become laggy when resizing the image above its original dimensions but there is also little to no benefit for it.
Of course this could also be an option instead of being the default forced behavior but I'm open to discussion.

feat: Limit max width/height of resize to the image to disallow upscaling

---

apps/image-editor/index.d.ts

Index.d.ts fixed with missing parameters for correct working with TypeScript

fix: iterationCount redo/undo (fixed #795)

---

apps/vue-image-editor/src/ImageEditor.vue

fix: Vue wrapper instance options.
This PR fixes an issue with Vue wrapper component not setting editor options properly.

fix: Pass options prop to editor instance.

---

apps/image-editor/src/css/range.styl

fixed css property typo from `backbround-color` to `background-color`

fix: background-color property typo
